version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - cd ./frontend && npm install
  pre_build:
    commands:
      - echo "Linting the React application..."
      - cd ./frontend && npm run lint
  build_backend:
    commands:
      - echo "Deploying the sam application"
      - cd backend/
      - sam build
      - sam deploy --stack-name ${STACK_NAME} \
        --capabilities CAPABILITY_NAMED_IAM \
        --region ${AWS_REGION} \
        --s3-bucket ${ARTIFACTS_BUCKET} \
        --no-fail-on-empty-changeset \
  build_frontend:
    commands:
      - echo "Building the React application..."
      - cd ./frontend && npm run build
      - s3 cp ./build s3://${STACK_NAME}-web-app-s3-bucket --recursive
  post_build:
    commands:
      - echo "finished deploying"
  artifacts:
    files:
      - '**/*'

