version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - docker pull node
      - echo "Installing dependencies..."
      - cd ./frontend 
      - docker run --rm -it -v $PWD:/app -w /app npm install
  pre_build:
    commands:
      - echo "About to deploy the application"
  build:
    commands:
      - echo "Deploying the sam application"
      - cd ../backend
      - sam build
      - sam deploy --stack-name ${STACK_NAME} \
        --capabilities CAPABILITY_NAMED_IAM \
        --region ${AWS_REGION} \
        --s3-bucket ${ARTIFACTS_BUCKET} \
        --no-fail-on-empty-changeset \
      - echo "Building the React application..."
      - cd ../frontend 
      - docker run --rm -it -v $PWD:/app -w /app npm run build
      - s3 cp ./build s3://${STACK_NAME}-web-app-s3-bucket --recursive
  post_build:
    commands:
      - echo "finished deploying"