version: '3.8'
services:

  install_frontend:
    image: node:16-alpine
    command: npm install
    working_dir: /app 
    volumes: 
    - ./frontend:/app
  
  build_frontend:
    image: node:16-alpine
    command: npm run build
    working_dir: /app
    environment:
    - REACT_APP_URL='/' 
    volumes: 
    - ./frontend:/app
    depends_on:
      install_frontend:
        condition: service_completed_successfully

  handle_backend:
    image: sam-builder
    command: ./deploy-script.sh
    environment:
      - AWS_REGION=${AWS_REGION}
      - LAMBDA_ECR_REPO=${LAMBDA_ECR_REPO}
      - STACK_NAME=${STACK_NAME}
      - BUCKET_NAME=${BUCKET_NAME}
    working_dir: /app 
    volumes:
    - ./backend:/app
    - /var/run/docker.sock:/var/run/docker.sock
    - ~/.aws/credentials:/root/.aws/credentials


