version: '3.8'
services:

  install_frontend:
    image: node:16-alpine
    command: npm install
    working_dir: /app 
    volumes: 
    - ./frontend:/app
  
  build_frontend:
    image: node:16-alpine
    command: npm run build
    working_dir: /app 
    volumes: 
    - ./frontend:/app
    depends_on:
      install_frontend:
        condition: service_completed_successfully

  build_backend:
    image: public.ecr.aws/sam/build-python3.9:1.95.0-20230810182727
    command: sam build -u
    working_dir: /app 
    volumes:
    - ./backend:/app
    - /var/run/docker.sock:/var/run/docker.sock

  deploy_backend:
    image: public.ecr.aws/sam/build-python3.9:1.95.0-20230810182727
    command: sam deploy --stack-name ${STACK_NAME} --capabilities CAPABILITY_IAM --region ${AWS_REGION} --resolve-s3 --resolve-image-repos --no-fail-on-empty-changeset --parameter-overrides ParameterKey=BUCKENT_NAME,ParameterValue=${BUCKET_NAME} ParameterKey=IMAGE_URI,ParameterValue=${LAMBDA_ECR_REPO}
    working_dir: /app 
    volumes:
    - ./backend:/app
    depends_on:
      build_backend:
        condition: service_completed_successfully  

