version: '3.8'
services:

  install_frontend:
    image: node:16-alpine
    command: npm install
    working_dir: /app 
    volumes: 
    - ./frontend:/app
  
  build_frontend:
    image: node:16-alpine
    command: npm run build
    working_dir: /app 
    volumes: 
    - ./frontend:/app
    depends_on:
      install_frontend:
        condition: service_completed_successfully

  build_backend:
    image: sam-builder
    command: ./deploy-script.sh
    environment:
      - AWS_REGION=us-east-1
      - LAMBDA_ECR_REPO=110828812774.dkr.ecr.us-east-1.amazonaws.com/testrepo
    working_dir: /app 
    volumes:
    - ./backend:/app
    - /var/run/docker.sock:/var/run/docker.sock
    - ~/.aws/credentials:/root/.aws/credentials


  deploy_backend:
    image: sam-builder
    command: sam deploy --stack-name ${STACK_NAME} --capabilities CAPABILITY_IAM --region ${AWS_REGION} --resolve-s3  --resolve-image-repos --template-file /app/packaged-template.yaml --no-fail-on-empty-changeset --parameter-overrides ParameterKey=BucketPrefix,ParameterValue=${BUCKET_NAME} 
    working_dir: /app 
    volumes:
    - ./backend:/app
    depends_on:
      build_backend:
        condition: service_completed_successfully  

