version: '3.8'
services:

  install_frontend:
    image: node:16-alpine
    command: npm install
    working_dir: /app 
    volumes: 
    - ./frontend:/app
  
  build_frontend:
    image: node:16-alpine
    command: npm run build
    working_dir: /app 
    volumes: 
    - ./frontend:/app
    depends_on:
      install_frontend:
        condition: service_completed_successfully

  handle_backend:
    image: sam-builder
    command: ./deploy-script.sh
    environment:
      - AWS_REGION=us-east-1
      - LAMBDA_ECR_REPO=110828812774.dkr.ecr.us-east-1.amazonaws.com/testrepo
    working_dir: /app 
    volumes:
    - ./backend:/app
    - /var/run/docker.sock:/var/run/docker.sock
    - ~/.aws/credentials:/root/.aws/credentials


