version: '3.8'
services:

  install_frontend:
    image: node:16-alpine
    command: npm install
    working_dir: /app 
    volumes: 
    - ./frontend:/app
  
  build_frontend:
    image: node:16-alpine
    command: npm run build
    working_dir: /app 
    volumes: 
    - ./frontend:/app
    depends_on:
      install_frontend:
        condition: service_completed_successfully


  build_backend:
    image: public.ecr.aws/sam/build-python3.9:1.95.0-20230810182727
    command: sam build
    working_dir: /app 
    volumes:
    - ./backend:/app
    - /var/run/docker.sock:/var/run/docker.sock


  deploy_backend:
    image: public.ecr.aws/sam/build-python3.9:1.95.0-20230810182727
    command: >
        sam deploy --stack-name ${STACK_NAME} \
        --capabilities CAPABILITY_NAMED_IAM \
        --region ${AWS_REGION} \
        --s3-bucket ${ARTIFACTS_BUCKET} \
        --no-fail-on-empty-changeset \
        --image-repository ${LAMBDA_ECR_REPO}
        --parameter-overrides BUCKENT_NAME=${BUCKET_NAME}
    working_dir: /app 
    volumes:
    - ./backend:/app
    depends_on:
      build_backend:
        condition: service_completed_successfully  

