AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  BucketPrefix:
    Type: String
    Description: This is the name of the static website
  
  DnsRecord:
    Type: String
    Description: The name of DNS of the application
    Default: musicviz.earbuddy.link


Resources:
  ScoresBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: socres-bucket-music-vis

  WorkerBroker:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: music-vis-worker-broker
      RedrivePolicy:
        maxReceiveCount: 5
        deadLetterTargetArn: !GetAtt BrokerDLQ.Arn
      VisibilityTimeout: 90

  BrokerDLQ:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: worker-dlq


  #### Frontend React Application hosting ####
  MusicVizFrontend:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Fn::Join:
          - '-'
          -  - !Sub ${AWS::StackName}
             - !Ref BucketPrefix 
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    #### Bucket Policy to allow CDN https access ####
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MusicVizFrontendPolicy
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: 
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Action: 's3:GetObject'
            Resource: !Sub
              - 'arn:aws:s3:::${Bucket}/*'
              - Bucket: !Ref MusicVizFrontend
      Bucket: !Ref MusicVizFrontend


  #### CDN For Client side ####
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
       DistributionConfig:
        Origins:
          - Id: MusicVizFrontend
            DomainName: !GetAtt MusicVizFrontend.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
          - Id: Backend
            DomainName: !Sub "${UploadScoreApi}.execute-api.${AWS::Region}.amazonaws.com"
            OriginPath: "/dev"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: MusicVizFrontend
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: true
        CacheBehaviors:
          - TargetOriginId: Backend
            PathPattern: "api/*"
            DefaultTTL: 0
            MinTTL: 0
            MaxTTL: 0
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET,HEAD,OPTIONS,PUT,PATCH,POST,DELETE]
            ForwardedValues:
              QueryString: true
        Enabled: true
        Aliases:
        - !Ref DnsRecord
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
          AcmCertificateArn: !Ref MusicVizCertificate
        DefaultRootObject: index.html   

  MusicVizCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DnsRecord
      DomainValidationOptions:
        - DomainName: !Ref DnsRecord
          HostedZoneId: Z0928443148KWAYRV1TH7
      ValidationMethod: DNS

  MusicVizDNSAliasRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: Z0928443148KWAYRV1TH7
      RecordSets:
        - Name: !Ref DnsRecord
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt
              - CloudFrontDistribution
              - DomainName
        - Name: !Ref DnsRecord
          Type: AAAA
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt
              - CloudFrontDistribution
              - DomainName

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties: 
      CloudFrontOriginAccessIdentityConfig: 
        Comment: CloudFront access identity     

  #### Backend lambda worker  #####

  CheckerFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.9
      CodeUri: ./checker
      Role: !GetAtt CheckerExecutionRole.Arn
      Environment:
        Variables:
          WEBSOCKET_API: !Sub https://${CheckerWebSocket}.execute-api.${AWS::Region}.amazonaws.com/dev/
          S3_BUCKET_NAME: !Ref ScoresBucket
          QUEUE_URL: !GetAtt WorkerBroker.QueueUrl
  
  WorkerFunction:
    Type: 'AWS::Serverless::Function'
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./worker
      DockerTag: latest
    Properties:
      FunctionName: MusicVizWorker
      PackageType: Image
      MemorySize: 256
      Policies: AmazonDynamoDBFullAccess
      Timeout: 300
      Architectures:
        - x86_64
      Events:
        OnUpload:
          Type: Api
          Properties:
            Path: /api/upload
            Method: put
            RestApiId: !Ref UploadScoreApi
            RequestParameters:
            - method.request.querystring.startMeasure:
              Required: true
            - method.request.querystring.endMeasure:
              Required: true 
        Options:
          Type: Api
          Properties:
            Path: /api/upload
            Method: OPTIONS
            RestApiId: !Ref UploadScoreApi

 CheckerWebSocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: CheckerWebSockerApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action
  CheckerIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: CheckerWebSocket
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Checker.Arn}/invocations
      IntegrationMethod: POST
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: CheckerWebSocket
      RouteKey: $connect
      OperationName: ConnectRoute
      Target: !Join
        - /
        - - integrations 
          - !Ref CheckerIntegration        
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: CheckerWebSocket
      RouteKey: $disconnect
      OperationName: DisconnectRoute
      Target: !Join
        - /
        - - integrations 
          - !Ref CheckerIntegration
  OnCheckRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: CheckerWebSocket
      RouteKey: onCheck
      OperationName: ProcessRoute
      Target: !Join
        - /
        - - integrations 
          - !Ref CheckerIntegration
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - OnCheckRoute
    Properties:
      ApiId: !Ref CheckerWebSocket
      # StageName: !Ref Stage
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: dev
      Description: Version 'dev'
      DeploymentId: !Ref Deployment
      ApiId: !Ref CheckerWebSocket

  

  ###### Api endpoint ########
  UploadScoreApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: dev
      EndpointConfiguration:
        Type: EDGE
      Cors:
        AllowMethods: "'PUT'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
      BinaryMediaTypes:
        - '*/*'

Outputs:
  ApiEndpoint:
    Description: API endpoint URL
    Value: !Sub 'https://${UploadScoreApi}.execute-api.${AWS::Region}.amazonaws.com/dev'

  Website:
    Value: !GetAtt CloudFrontDistribution.DomainName
