Resources:
  ScoresBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:provider.environment.SCORES_BUCKET}

  MusicVizFrontend:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Fn::Join:
          - '-'
          -  - !Sub ${AWS::StackName}
             - frontend-app
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
        
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MusicVizFrontend 
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: MusicVizClientAccessPolicy
            Effect: Allow
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${MusicVizFrontend}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"
