Resources:
  MusicVizDNSAliasRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: Z0928443148KWAYRV1TH7
      RecordSets:
        - Name: ${self:provider.environment.DOMAIN_NAME}
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt
              - CloudFrontDistribution
              - DomainName
        - Name: ${self:provider.environment.DOMAIN_NAME}
          Type: AAAA
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt
              - CloudFrontDistribution
              - DomainName
  MusicVizCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: ${self:provider.environment.DOMAIN_NAME}
      DomainValidationOptions:
        - DomainName: ${self:provider.environment.DOMAIN_NAME}
          HostedZoneId: Z0928443148KWAYRV1TH7
      ValidationMethod: DNS